# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
GITHUB_COMMENT_REPORTER: false
DISABLE_LINTERS:
  # Pylint errors on missing dependencies, and is redundant with ruff.
  - PYTHON_PYLINT
  # Pyright errors on missing dependencies.
  - PYTHON_PYRIGHT
  # yamllint is sufficient for us.
  - YAML_PRETTIER
DISABLE_ERRORS_LINTERS:
  # This may be informative but doesn't need to break the build.
  - COPYPASTE_JSCPD
  # Making optional to not block builds, even though it's still important!
  - SPELL_CSPELL
PYTHON_ISORT_ARGUMENTS: "--src src"
SPELL_CSPELL_PRE_COMMANDS:
  - command: >-
      cp .cspell.json /tmp/cspell.json.orig &&
      curl -sSf --connect-timeout 5 --max-time 15
      https://raw.githubusercontent.com/linuxfoundation/lfx-public-workflows/a93335d2abc2a2e2bb1b7a4cdefbbf15351681ce/cspell/flagwords.json.snippet
      -o /tmp/flagwords.json.snippet &&
      sed -i -e '/"flagWords": \[\]/{r /tmp/flagwords.json.snippet' -e 'd}' .cspell.json
    cwd: "workspace"
    continue_if_failed: false
SPELL_CSPELL_POST_COMMANDS:
  - command: cp /tmp/cspell.json.orig .cspell.json
    cwd: "workspace"
